server:
  port: 6618

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-qn7ic9iq.sql.tencentcdb.com:22277/scancall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: s8pK9fXX


mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
